### ISSUE TITLE
Multiple levels 

### ISSUE THREAD

**Issue by DaneShrewsbury2288** [Stegler/Netscape#12]
Create multiple maps/levels that are all connected. Once you grab all the coins/rewards on one level (Either the level automatically ends or a door appears that will take you to the next level/map) 

- [ ] Create multiple maps / levels.

- [ ] Connect the levels via doorway/ladder or something. 

![2d door-sprite](https://user-images.githubusercontent.com/48495423/60763071-8a875280-a021-11e9-8efe-1a1c5d2dc747.png)

**Comment by elvykiung** [comment]
put in icebox
